'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {

    return queryInterface.bulkInsert('Memes', [
      {"name":"One Does Not Simply","url":"https://i.imgflip.com/1bij.jpg"},
      {"name":"Batman Slapping Robin","url":"https://i.imgflip.com/9ehk.jpg"},
      {"name":"Ancient Aliens","url":"https://i.imgflip.com/26am.jpg"},
      {"name":"Futurama Fry","url":"https://i.imgflip.com/1bgw.jpg"},
      {"name":"X, X Everywhere","url":"https://i.imgflip.com/7g1q.jpg"},
      {"name":"Waiting Skeleton","url":"https://i.imgflip.com/2fm6x.jpg"},
      {"name":"The Most Interesting Man In The World","url":"https://i.imgflip.com/1bh8.jpg"},
      {"name":"Leonardo Dicaprio Cheers","url":"https://i.imgflip.com/39t1o.jpg"},
      {"name":"First World Problems","url":"https://i.imgflip.com/1bhf.jpg"},
      {"name":"Oprah You Get A","url":"https://i.imgflip.com/gtj5t.jpg"},
      {"name":"Y U No","url":"https://i.imgflip.com/1bh3.jpg"},
      {"name":"Boardroom Meeting Suggestion","url":"https://i.imgflip.com/m78d.jpg"},
      {"name":"That Would Be Great","url":"https://i.imgflip.com/c2qn.jpg"},
      {"name":"Doge","url":"https://i.imgflip.com/4t0m5.jpg"},
      {"name":"Bad Luck Brian","url":"https://i.imgflip.com/1bip.jpg"},
      {"name":"Brace Yourselves X is Coming","url":"https://i.imgflip.com/1bhm.jpg"},
      {"name":"Captain Picard Facepalm","url":"https://i.imgflip.com/wczz.jpg"},
      {"name":"Yall Got Any More Of","url":"https://i.imgflip.com/7zq97.jpg"},
      {"name":"Creepy Condescending Wonka","url":"https://i.imgflip.com/1bim.jpg"},
      {"name":"Third World Skeptical Kid","url":"https://i.imgflip.com/265k.jpg"},
      {"name":"But Thats None Of My Business","url":"https://i.imgflip.com/9sw43.jpg"},
      {"name":"Success Kid","url":"https://i.imgflip.com/1bhk.jpg"},
      {"name":"Star Wars Yoda","url":"https://i.imgflip.com/8k0sa.jpg"},
      {"name":"X All The Y","url":"https://i.imgflip.com/1bh9.jpg"},
      {"name":"Grumpy Cat","url":"https://i.imgflip.com/8p0a.jpg"},
      {"name":"Black Girl Wat","url":"https://i.imgflip.com/8h0c8.jpg"},
      {"name":"Matrix Morpheus","url":"https://i.imgflip.com/25w3.jpg"},
      {"name":"Disaster Girl","url":"https://i.imgflip.com/23ls.jpg"},
      {"name":"Dr Evil Laser","url":"https://i.imgflip.com/odluv.jpg"},
      {"name":"The Rock Driving","url":"https://i.imgflip.com/grr.jpg"},
      {"name":"Philosoraptor","url":"https://i.imgflip.com/1bgs.jpg"},
      {"name":"Grandma Finds The Internet","url":"https://i.imgflip.com/1bhw.jpg"},
      {"name":"Face You Make Robert Downey Jr","url":"https://i.imgflip.com/5mcpl.jpg"},
      {"name":"Picard Wtf","url":"https://i.imgflip.com/59qi.jpg"},
      {"name":"Evil Toddler","url":"https://i.imgflip.com/51s5.jpg"},
      {"name":"Finding Neverland","url":"https://i.imgflip.com/3pnmg.jpg"},
      {"name":"Third World Success Kid","url":"https://i.imgflip.com/265j.jpg"},
      {"name":"Dont You Squidward","url":"https://i.imgflip.com/26br.jpg"},
      {"name":"10 Guy","url":"https://i.imgflip.com/269s.jpg"},
      {"name":"Am I The Only One Around Here","url":"https://i.imgflip.com/5kdc.jpg"},
      {"name":"Confession Bear","url":"https://i.imgflip.com/25wb.jpg"},
      {"name":"Too Damn High","url":"https://i.imgflip.com/1bik.jpg"},
      {"name":"Awkward Moment Sealion","url":"https://i.imgflip.com/86vlk.jpg"},
      {"name":"Sparta Leonidas","url":"https://i.imgflip.com/46rh.jpg"},
      {"name":"Maury Lie Detector","url":"https://i.imgflip.com/9iz9.jpg"},
      {"name":"Skeptical Baby","url":"https://i.imgflip.com/26hb.jpg"},
      {"name":"Yo Dawg Heard You","url":"https://i.imgflip.com/26hg.jpg"},
      {"name":"Laughing Men In Suits","url":"https://i.imgflip.com/jrj7.jpg"},
      {"name":"Put It Somewhere Else Patrick","url":"https://i.imgflip.com/1bil.jpg"},
      {"name":"Socially Awesome Awkward Penguin","url":"https://i.imgflip.com/1bio.jpg"},
      {"name":"Be Like Bill","url":"https://i.imgflip.com/xh3me.jpg"},
      {"name":"Aint Nobody Got Time For That","url":"https://i.imgflip.com/9hhr.jpg"},
      {"name":"Ill Just Wait Here","url":"https://i.imgflip.com/2cp1.jpg"},
      {"name":"Say That Again I Dare You","url":"https://i.imgflip.com/2nuc.jpg"},
      {"name":"Mugatu So Hot Right Now","url":"https://i.imgflip.com/cv1y0.jpg"},
      {"name":"Conspiracy Keanu","url":"https://i.imgflip.com/1bin.jpg"},
      {"name":"Aaaaand Its Gone","url":"https://i.imgflip.com/gft6.jpg"},
      {"name":"Bad Pun Dog","url":"https://i.imgflip.com/7dusq.jpg"},
      {"name":"Back In My Day","url":"https://i.imgflip.com/fecg.jpg"},
      {"name":"Steve Harvey","url":"https://i.imgflip.com/32sx.jpg"},
      {"name":"Archer","url":"https://i.imgflip.com/6bt40.jpg"},
      {"name":"Spongegar","url":"https://i.imgflip.com/14wa6i.jpg"},
      {"name":"Uncle Sam","url":"https://i.imgflip.com/1x6f.jpg"},
      {"name":"This Is Where I'd Put My Trophy If I Had One","url":"https://i.imgflip.com/1wz1x.jpg"},
      {"name":"Imagination Spongebob","url":"https://i.imgflip.com/3i7p.jpg"},
      {"name":"See Nobody Cares","url":"https://i.imgflip.com/3vzej.jpg"},
      {"name":"Liam Neeson Taken","url":"https://i.imgflip.com/4vy0.jpg"},
      {"name":"Look At Me","url":"https://i.imgflip.com/hmt3v.jpg"},
      {"name":"Arthur Fist","url":"https://i.imgflip.com/1866qe.jpg"},
      {"name":"Hide the Pain Harold","url":"https://i.imgflip.com/gk5el.jpg"},
      {"name":"And everybody loses their minds","url":"https://i.imgflip.com/12dxv.jpg"},
      {"name":"Pepperidge Farm Remembers","url":"https://i.imgflip.com/qep4.jpg"},
      {"name":"I Should Buy A Boat Cat","url":"https://i.imgflip.com/tau4.jpg"},
      {"name":"Buddy Christ","url":"https://i.imgflip.com/dnn.jpg"},
      {"name":"Jackie Chan WTF","url":"https://i.imgflip.com/8u2b.jpg"},
      {"name":"Scumbag Steve","url":"https://i.imgflip.com/1bgy.jpg"},
      {"name":"Gollum","url":"https://i.imgflip.com/em3r.jpg"},
      {"name":"Unpopular Opinion Puffin","url":"https://i.imgflip.com/4mcml.jpg"},
      {"name":"Ryan Gosling","url":"https://i.imgflip.com/8csq.jpg"},
      {"name":"Its Not Going To Happen","url":"https://i.imgflip.com/6656q.jpg"},
      {"name":"Shut Up And Take My Money Fry","url":"https://i.imgflip.com/3si4.jpg"},
      {"name":"Good Fellas Hilarious","url":"https://i.imgflip.com/s4f1k.jpg"},
      {"name":"Marvel Civil War 1","url":"https://i.imgflip.com/govs4.jpg"},
      {"name":"Dave Chappelle","url":"https://i.imgflip.com/lgxgt.jpg"},
      {"name":"Overly Attached Girlfriend","url":"https://i.imgflip.com/25w8.jpg"},
      {"name":"Ermahgerd Berks","url":"https://i.imgflip.com/26ae.jpg"},
      {"name":"Spiderman Peter Parker","url":"https://i.imgflip.com/2b5p.jpg"},
      {"name":"Spiderman Computer Desk","url":"https://i.imgflip.com/tas1.jpg"},
      {"name":"Cute Cat","url":"https://i.imgflip.com/4xgqu.jpg"},
      {"name":"Peter Griffin News","url":"https://i.imgflip.com/7n5z.jpg"},
      {"name":"I'm The Captain Now","url":"https://i.imgflip.com/hlmst.jpg"},
      {"name":"Star Wars No","url":"https://i.imgflip.com/bfexh.jpg"},
      {"name":"Surprised Koala","url":"https://i.imgflip.com/ljk.jpg"},
      {"name":"Dwight Schrute","url":"https://i.imgflip.com/1bhu.jpg"},
      {"name":"Jack Sparrow Being Chased","url":"https://i.imgflip.com/9vct.jpg"},
      {"name":"Kill Yourself Guy","url":"https://i.imgflip.com/3oyi.jpg"},
      {"name":"Simba Shadowy Place","url":"https://i.imgflip.com/7yk6.jpg"},
      {"name":"Kevin Hart The Hell","url":"https://i.imgflip.com/5p31.jpg"},
      {"name":"Obi Wan Kenobi","url":"https://i.imgflip.com/8rwb.jpg"},
      {"name":"Leonardo Dicaprio Wolf Of Wall Street","url":"https://i.imgflip.com/af002.jpg"}]
     );

  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Memes');
  }
};
