'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {

    return queryInterface.bulkInsert('Memes', [
      { name: 'One Does Not Simply',
        url: 'https://i.imgflip.com/1bij.jpg',
        imgFlipID: '61579' },
      { name: 'Batman Slapping Robin',
        url: 'https://i.imgflip.com/9ehk.jpg',
        imgFlipID: '438680' },
      { name: 'Ancient Aliens',
        url: 'https://i.imgflip.com/26am.jpg',
        imgFlipID: '101470' },
      { name: 'Futurama Fry',
        url: 'https://i.imgflip.com/1bgw.jpg',
        imgFlipID: '61520' },
      { name: 'X, X Everywhere',
        url: 'https://i.imgflip.com/7g1q.jpg',
        imgFlipID: '347390' },
      { name: 'Waiting Skeleton',
        url: 'https://i.imgflip.com/2fm6x.jpg',
        imgFlipID: '4087833' },
      { name: 'The Most Interesting Man In The World',
        url: 'https://i.imgflip.com/1bh8.jpg',
        imgFlipID: '61532' },
      { name: 'Leonardo Dicaprio Cheers',
        url: 'https://i.imgflip.com/39t1o.jpg',
        imgFlipID: '5496396' },
      { name: 'First World Problems',
        url: 'https://i.imgflip.com/1bhf.jpg',
        imgFlipID: '61539' },
      { name: 'Oprah You Get A',
        url: 'https://i.imgflip.com/gtj5t.jpg',
        imgFlipID: '28251713' },
      { name: 'Y U No',
        url: 'https://i.imgflip.com/1bh3.jpg',
        imgFlipID: '61527' },
      { name: 'Boardroom Meeting Suggestion',
        url: 'https://i.imgflip.com/m78d.jpg',
        imgFlipID: '1035805' },
      { name: 'That Would Be Great',
        url: 'https://i.imgflip.com/c2qn.jpg',
        imgFlipID: '563423' },
      { name: 'Bad Luck Brian',
        url: 'https://i.imgflip.com/1bip.jpg',
        imgFlipID: '61585' },
      { name: 'Doge',
        url: 'https://i.imgflip.com/4t0m5.jpg',
        imgFlipID: '8072285' },
      { name: 'Captain Picard Facepalm',
        url: 'https://i.imgflip.com/wczz.jpg',
        imgFlipID: '1509839' },
      { name: 'Brace Yourselves X is Coming',
        url: 'https://i.imgflip.com/1bhm.jpg',
        imgFlipID: '61546' },
      { name: 'Yall Got Any More Of',
        url: 'https://i.imgflip.com/7zq97.jpg',
        imgFlipID: '13424299' },
      { name: 'Creepy Condescending Wonka',
        url: 'https://i.imgflip.com/1bim.jpg',
        imgFlipID: '61582' },
      { name: 'Third World Skeptical Kid',
        url: 'https://i.imgflip.com/265k.jpg',
        imgFlipID: '101288' },
      { name: 'But Thats None Of My Business',
        url: 'https://i.imgflip.com/9sw43.jpg',
        imgFlipID: '16464531' },
      { name: 'X All The Y',
        url: 'https://i.imgflip.com/1bh9.jpg',
        imgFlipID: '61533' },
      { name: 'Success Kid',
        url: 'https://i.imgflip.com/1bhk.jpg',
        imgFlipID: '61544' },
      { name: 'Star Wars Yoda',
        url: 'https://i.imgflip.com/8k0sa.jpg',
        imgFlipID: '14371066' },
      { name: 'Grumpy Cat',
        url: 'https://i.imgflip.com/8p0a.jpg',
        imgFlipID: '405658' },
      { name: 'Black Girl Wat',
        url: 'https://i.imgflip.com/8h0c8.jpg',
        imgFlipID: '14230520' },
      { name: 'Matrix Morpheus',
        url: 'https://i.imgflip.com/25w3.jpg',
        imgFlipID: '100947' },
      { name: 'Disaster Girl',
        url: 'https://i.imgflip.com/23ls.jpg',
        imgFlipID: '97984' },
      { name: 'Dr Evil Laser',
        url: 'https://i.imgflip.com/odluv.jpg',
        imgFlipID: '40945639' },
      { name: 'The Rock Driving',
        url: 'https://i.imgflip.com/grr.jpg',
        imgFlipID: '21735' },
      { name: 'Philosoraptor',
        url: 'https://i.imgflip.com/1bgs.jpg',
        imgFlipID: '61516' },
      { name: 'Grandma Finds The Internet',
        url: 'https://i.imgflip.com/1bhw.jpg',
        imgFlipID: '61556' },
      { name: 'Face You Make Robert Downey Jr',
        url: 'https://i.imgflip.com/5mcpl.jpg',
        imgFlipID: '9440985' },
      { name: 'Picard Wtf',
        url: 'https://i.imgflip.com/59qi.jpg',
        imgFlipID: '245898' },
      { name: 'Evil Toddler',
        url: 'https://i.imgflip.com/51s5.jpg',
        imgFlipID: '235589' },
      { name: 'Finding Neverland',
        url: 'https://i.imgflip.com/3pnmg.jpg',
        imgFlipID: '6235864' },
      { name: 'Third World Success Kid',
        url: 'https://i.imgflip.com/265j.jpg',
        imgFlipID: '101287' },
      { name: 'Dont You Squidward',
        url: 'https://i.imgflip.com/26br.jpg',
        imgFlipID: '101511' },
      { name: 'Am I The Only One Around Here',
        url: 'https://i.imgflip.com/5kdc.jpg',
        imgFlipID: '259680' },
      { name: '10 Guy',
        url: 'https://i.imgflip.com/269s.jpg',
        imgFlipID: '101440' },
      { name: 'Awkward Moment Sealion',
        url: 'https://i.imgflip.com/86vlk.jpg',
        imgFlipID: '13757816' },
      { name: 'Confession Bear',
        url: 'https://i.imgflip.com/25wb.jpg',
        imgFlipID: '100955' },
      { name: 'Too Damn High',
        url: 'https://i.imgflip.com/1bik.jpg',
        imgFlipID: '61580' },
      { name: 'Sparta Leonidas',
        url: 'https://i.imgflip.com/46rh.jpg',
        imgFlipID: '195389' },
      { name: 'Skeptical Baby',
        url: 'https://i.imgflip.com/26hb.jpg',
        imgFlipID: '101711' },
      { name: 'Maury Lie Detector',
        url: 'https://i.imgflip.com/9iz9.jpg',
        imgFlipID: '444501' },
      { name: 'Laughing Men In Suits',
        url: 'https://i.imgflip.com/jrj7.jpg',
        imgFlipID: '922147' },
      { name: 'Put It Somewhere Else Patrick',
        url: 'https://i.imgflip.com/1bil.jpg',
        imgFlipID: '61581' },
      { name: 'Yo Dawg Heard You',
        url: 'https://i.imgflip.com/26hg.jpg',
        imgFlipID: '101716' },
      { name: 'Be Like Bill',
        url: 'https://i.imgflip.com/xh3me.jpg',
        imgFlipID: '56225174' },
      { name: 'Socially Awesome Awkward Penguin',
        url: 'https://i.imgflip.com/1bio.jpg',
        imgFlipID: '61584' },
      { name: 'Aint Nobody Got Time For That',
        url: 'https://i.imgflip.com/9hhr.jpg',
        imgFlipID: '442575' },
      { name: 'Ill Just Wait Here',
        url: 'https://i.imgflip.com/2cp1.jpg',
        imgFlipID: '109765' },
      { name: 'Conspiracy Keanu',
        url: 'https://i.imgflip.com/1bin.jpg',
        imgFlipID: '61583' },
      { name: 'Say That Again I Dare You',
        url: 'https://i.imgflip.com/2nuc.jpg',
        imgFlipID: '124212' },
      { name: 'Aaaaand Its Gone',
        url: 'https://i.imgflip.com/gft6.jpg',
        imgFlipID: '766986' },
      { name: 'Mugatu So Hot Right Now',
        url: 'https://i.imgflip.com/cv1y0.jpg',
        imgFlipID: '21604248' },
      { name: 'Bad Pun Dog',
        url: 'https://i.imgflip.com/7dusq.jpg',
        imgFlipID: '12403754' },
      { name: 'Back In My Day',
        url: 'https://i.imgflip.com/fecg.jpg',
        imgFlipID: '718432' },
      { name: 'Steve Harvey',
        url: 'https://i.imgflip.com/32sx.jpg',
        imgFlipID: '143601' },
      { name: 'Archer',
        url: 'https://i.imgflip.com/6bt40.jpg',
        imgFlipID: '10628640' },
      { name: 'Uncle Sam',
        url: 'https://i.imgflip.com/1x6f.jpg',
        imgFlipID: '89655' },
      { name: 'This Is Where I\'d Put My Trophy If I Had One',
        url: 'https://i.imgflip.com/1wz1x.jpg',
        imgFlipID: '3218037' },
      { name: 'Spongegar',
        url: 'https://i.imgflip.com/14wa6i.jpg',
        imgFlipID: '68690826' },
      { name: 'Imagination Spongebob',
        url: 'https://i.imgflip.com/3i7p.jpg',
        imgFlipID: '163573' },
      { name: 'Look At Me',
        url: 'https://i.imgflip.com/hmt3v.jpg',
        imgFlipID: '29617627' },
      { name: 'Arthur Fist',
        url: 'https://i.imgflip.com/1866qe.jpg',
        imgFlipID: '74191766' },
      { name: 'See Nobody Cares',
        url: 'https://i.imgflip.com/3vzej.jpg',
        imgFlipID: '6531067' },
      { name: 'Liam Neeson Taken',
        url: 'https://i.imgflip.com/4vy0.jpg',
        imgFlipID: '228024' },
      { name: 'Hide the Pain Harold',
        url: 'https://i.imgflip.com/gk5el.jpg',
        imgFlipID: '27813981' },
      { name: 'Pepperidge Farm Remembers',
        url: 'https://i.imgflip.com/qep4.jpg',
        imgFlipID: '1232104' },
      { name: 'And everybody loses their minds',
        url: 'https://i.imgflip.com/12dxv.jpg',
        imgFlipID: '1790995' },
      { name: 'I Should Buy A Boat Cat',
        url: 'https://i.imgflip.com/tau4.jpg',
        imgFlipID: '1367068' },
      { name: 'Jackie Chan WTF',
        url: 'https://i.imgflip.com/8u2b.jpg',
        imgFlipID: '412211' },
      { name: 'Scumbag Steve',
        url: 'https://i.imgflip.com/1bgy.jpg',
        imgFlipID: '61522' },
      { name: 'Buddy Christ',
        url: 'https://i.imgflip.com/dnn.jpg',
        imgFlipID: '17699' },
      { name: 'Gollum',
        url: 'https://i.imgflip.com/em3r.jpg',
        imgFlipID: '681831' },
      { name: 'Ryan Gosling',
        url: 'https://i.imgflip.com/8csq.jpg',
        imgFlipID: '389834' },
      { name: 'Its Not Going To Happen',
        url: 'https://i.imgflip.com/6656q.jpg',
        imgFlipID: '10364354' },
      { name: 'Good Fellas Hilarious',
        url: 'https://i.imgflip.com/s4f1k.jpg',
        imgFlipID: '47235368' },
      { name: 'Shut Up And Take My Money Fry',
        url: 'https://i.imgflip.com/3si4.jpg',
        imgFlipID: '176908' },
      { name: 'Marvel Civil War 1',
        url: 'https://i.imgflip.com/govs4.jpg',
        imgFlipID: '28034788' },
      { name: 'Unpopular Opinion Puffin',
        url: 'https://i.imgflip.com/4mcml.jpg',
        imgFlipID: '7761261' },
      { name: 'Dave Chappelle',
        url: 'https://i.imgflip.com/lgxgt.jpg',
        imgFlipID: '36061805' },
      { name: 'Spiderman Peter Parker',
        url: 'https://i.imgflip.com/2b5p.jpg',
        imgFlipID: '107773' },
      { name: 'Overly Attached Girlfriend',
        url: 'https://i.imgflip.com/25w8.jpg',
        imgFlipID: '100952' },
      { name: 'Ermahgerd Berks',
        url: 'https://i.imgflip.com/26ae.jpg',
        imgFlipID: '101462' },
      { name: 'Cute Cat',
        url: 'https://i.imgflip.com/4xgqu.jpg',
        imgFlipID: '8279814' },
      { name: 'Spiderman Computer Desk',
        url: 'https://i.imgflip.com/tas1.jpg',
        imgFlipID: '1366993' },
      { name: 'Surprised Koala',
        url: 'https://i.imgflip.com/ljk.jpg',
        imgFlipID: '27920' },
      { name: 'I\'m The Captain Now',
        url: 'https://i.imgflip.com/hlmst.jpg',
        imgFlipID: '29562797' },
      { name: 'Star Wars No',
        url: 'https://i.imgflip.com/bfexh.jpg',
        imgFlipID: '19194965' },
      { name: 'Peter Griffin News',
        url: 'https://i.imgflip.com/7n5z.jpg',
        imgFlipID: '356615' },
      { name: 'Jack Sparrow Being Chased',
        url: 'https://i.imgflip.com/9vct.jpg',
        imgFlipID: '460541' },
      { name: 'Kill Yourself Guy',
        url: 'https://i.imgflip.com/3oyi.jpg',
        imgFlipID: '172314' },
      { name: 'Dwight Schrute',
        url: 'https://i.imgflip.com/1bhu.jpg',
        imgFlipID: '61554' },
      { name: 'Simba Shadowy Place',
        url: 'https://i.imgflip.com/7yk6.jpg',
        imgFlipID: '371382' },
      { name: 'Kevin Hart The Hell',
        url: 'https://i.imgflip.com/5p31.jpg',
        imgFlipID: '265789' },
      { name: 'Obi Wan Kenobi',
        url: 'https://i.imgflip.com/8rwb.jpg',
        imgFlipID: '409403' },
      { name: 'Leonardo Dicaprio Wolf Of Wall Street',
        url: 'https://i.imgflip.com/af002.jpg',
        imgFlipID: '17496002' } ]
     );

  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Memes');
  }
};
